name: "virtualmin.dev: virtualmin/virtualmin-gpl"

on:
  push:
    branches:
      - master
    tags:
      - '*'
    
jobs:
  build:
    uses: webmin/webmin-ci-cd/.github/workflows/master-workflow.yml@main
    with:
      build-type: module
      project-name: ${{ github.event.repository.name }}
      tagged-release: ${{ startsWith(github.ref, 'refs/tags/') }}
    secrets: inherit
